
name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang-14 libc++-14-dev libc++abi-14-dev
      - name: Build, Compress, and Generate Checksum
        run: |
          rm -rf build
          mkdir build
          cd build
          CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install
          ls -l /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api*
          tar czf /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api.tar.gz /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api
          sha256sum /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api.tar.gz > /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api.tar.gz.sha256

      - name: Generate tag based on current date/time
        id: tag
        run: echo "TAG=v$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
          files: /home/runner/work/telegram-bot-api/telegram-bot-api/bin/telegram-bot-api.tar.gz
